version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image:
      mongo:6.0.6
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

